apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-nodeport-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30103
  type: NodePort
